# 4.4 퍼셉트론은 어떻게 학습할까?

이번 파트에서는 퍼셉트론이 정답을 찾아가는 '학습'의 원리를 알아봄

핵심은 **손실 함수**와 **경사 하강법**

### 1. 손실 함수(Loss Function): 내가 얼마나 틀렸지?
- 손실 함수는 현재 신경망이 정답과 얼마나 다른지, 즉 '오류의 양'을 숫자로 나타내주는 함수
- 신경망의 목표는 이 손실 함수의 값을 **최대한 0에 가깝게** 만드는 것

### 2. 경사 하강법(Gradient Descent): 정답을 향해 한 걸음씩
- 손실 함수 값이 가장 작아지는 지점(산의 가장 낮은 곳)을 찾아가는 방법
- 함수의 기울기(미분값)를 계산해서, 기울기가 가리키는 방향의 **반대 방향으로** 가중치(w)를 조금씩 이동
- 이때 얼만큼 이동할지를 정하는 것이 바로 **학습률(learning rate, ρ)**

### 3. 퍼셉트론 학습의 3단계
신경망 학습은 아래 3단계를 계속 반복하는 과정
1.  **① 전방 계산**: 현재 가중치로 결과를 예측해본다
2.  **② 오차 계산**: 예측값과 실제 정답(레이블)을 비교해 오차를 계산한다
3.  **③ 후방 가중치 갱신**: 계산된 오차를 바탕으로 가중치를 더 나은 방향으로 업데이트한다

(이 파트에서는 코딩 없이 개념만 이해하고 넘어감)

# 4.5 현대 기계 학습으로 확장하기

방금 배운 경사 하강법은 데이터가 수백만 개가 넘는 현대 딥러닝에 그대로 적용하기엔 너무 느림

그래서 나온 것이 바로 **스토캐스틱 경사 하강법(SGD)**

- **배치(Batch) vs 스토캐스틱(Stochastic)**
    - **배치 경사 하강법**: 전체 훈련 데이터를 **한 번에** 다 보고 가중치를 한 번 업데이트,
    정확하지만 느림
    - **스토캐스틱 경사 하강법(SGD)**: 전체 데이터를 **작은 묶음(미니 배치)**으로 나눈 뒤, 미니 배치 하나를 처리할 때마다 가중치를 업데이트
    
    조금 부정확할 순 있지만 훨씬 빠르고, 실제로는 성능도 더 잘 나오는 경우가 많다고 함

이제부터 우리가 할 실습은 바로 이 SGD 방식

# 4.6 퍼셉트론 프로그래밍 실습

이제 이론을 바탕으로 직접 퍼셉트론을 만들자

`scikit-learn` 라이브러리를 사용하면 아주 간단하게 구현

## 실습 1: 간단한 OR 데이터 문제

가장 기초적인 OR 논리 문제를 퍼셉트론을 해보자

아래 코드를 직접 따라 입력

In [8]:
# [프로그램 4-1] OR 데이터에 퍼셉트론 적용
# 필요한 라이브러리
from sklearn.linear_model import Perceptron
import numpy as np

# 훈련 집합을 준비 X는 데이터, y는 정답 레이블
X = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [-1, 1, 1, 1]

# 1. 모델 객체 생성
p = Perceptron()

# 2. 모델 학습 (fit 함수가 바로 경사 하강법으로 최적의 가중치를 찾는 과정)
p.fit(X, y)

# 3. 결과 확인
print("학습된 퍼셉트론의 매개변수 (가중치 w):", p.coef_)
print("학습된 퍼셉트론의 매개변수 (바이어스 w0):", p.intercept_)
print("훈련 집합에 대한 예측:", p.predict(X))
print("정확률 측정:", p.score(X, y) * 100, "%")

# ---- 다 같이 토의해볼 점 ----
# 1. 학습된 가중치와 바이어스 값이 어떤 의미?
# 2. 왜 정확도가 100%가 나왔을까?

학습된 퍼셉트론의 매개변수 (가중치 w): [[2. 2.]]
학습된 퍼셉트론의 매개변수 (바이어스 w0): [-1.]
훈련 집합에 대한 예측: [-1  1  1  1]
정확률 측정: 100.0 %


## 토의 답안 예시



### 1. 학습된 가중치와 바이어스 값이 어떤 의미?

퍼셉트론이 찾은 **최적의 '구분선'**

숫자들로 만든 직선으로 +1이랑 -1을 나누는 것

가중치는 각 데이터의 중요도, 바이어스는 그 선의 위치를 정함

### 2. 왜 정확도가 100%가 나왔을까?

 OR 데이터는 '선형 분리'가 가능함

 직선 하나로 정답이랑 오답을 완벽하게 나눌 수 있음

 퍼셉트론은 이런 문제를 푸는 데 최적화되어 있어서 100%가 나온 것

## 실습 2: 필기 숫자 데이터 인식

이번엔 좀 더 복잡한 필기 숫자 데이터를 퍼셉트론으로 인식시켜 보자

이 실습을 통해 우리는 **기계 학습 프로그래밍의 공통적인 패턴**을 발견할 수 있다

In [9]:
# [프로그램 4-2] 필기 숫자 데이터에 퍼셉트론 적용
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import numpy as np

# 1. 데이터 읽기 및 분할
digit = datasets.load_digits()
# 훈련 데이터와 테스트 데이터로 6:4 분할
x_train, x_test, y_train, y_test = train_test_split(digit.data, digit.target, train_size=0.6)

# 2. 모델 객체 생성 및 학습
# sklearn의 Perceptron은 여러 클래스(다중 분류)를 자동 지원
p = Perceptron(max_iter=100, eta0=0.001, verbose=0)
p.fit(x_train, y_train)

# 3. 예측
res = p.predict(x_test)

# 4. 성능 평가 (혼동 행렬)
conf = np.zeros((10, 10))
for i in range(len(res)):
  conf[res[i]][y_test[i]] += 1
print(conf)

# 정확률 계산
no_correct = 0
for i in range(10):
  no_correct += conf[i][i]
accuracy = no_correct / len(res)
print("테스트 집합에 대한 정확률은", accuracy * 100, "%입니다.")

# ---- 다 같이 토의해볼 점 ----
# 1. OR 문제와 이 문제의 코드 구조가 어떻게 비슷한가? (기계 학습 디자인 패턴)
# 2. 왜 이번에는 정확도가 100%가 아닐까? (퍼셉트론의 한계)
# 3. 혼동 행렬을 보니, 퍼셉트론이 어떤 숫자들을 주로 헷갈려 하나?

[[68.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 66.  0.  0.  1.  0.  0.  0.  5.  0.]
 [ 0.  0. 68.  1.  0.  0.  0.  0.  3.  0.]
 [ 0.  0.  1. 68.  0.  0.  0.  0.  2.  1.]
 [ 1.  1.  0.  0. 76.  0.  0.  4.  6.  1.]
 [ 1.  0.  0.  1.  0. 74.  0.  0.  6.  2.]
 [ 0.  1.  0.  0.  0.  0. 85.  0.  3.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 69.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0. 39.  0.]
 [ 0.  2.  0.  0.  0.  2.  0.  0.  2. 58.]]
테스트 집합에 대한 정확률은 93.3240611961057 %입니다.


## 토의 답안 예시

### 1. OR 문제와 이 문제의 코드 구조가 어떻게 비슷한가? (기계 학습 디자인 패턴)

둘 다 똑같은 **'디자인 패턴'**을 따르기 때문

데이터 준비 → 모델 생성 → 학습 → 예측/평가


### 2. 왜 이번에는 정확도가 100%가 아닐까? (퍼셉트론의 한계)

필기 숫자 데이터는 선형 분리가 안돼서

3이랑 8처럼 헷갈리는 데이터들을 직선 하나로 깔끔하게 나눌 수가 없음

퍼셉트론은 직선밖에 못 그으니까 한계가 있고, 그래서 100%가 안 나옴

### 3. 혼동 행렬을 보니, 퍼셉트론이 어떤 숫자들을 주로 헷갈려 하나?

혼동 행렬에서 대각선 빼고 나머지 부분을 보면 됨

거기가 다 틀린 것들

예를 들면, 8로 예측했는데 실제론 1이나 3인 경우

모델이 어떤 숫자들을 헷갈려 하는지 바로 보임